---
- hosts: all
  tasks:
    - group_by: key=os_{{ ansible_distribution }}

- hosts: os_Gentoo
  gather_facts: False
  roles:
    - gentoo

- hosts: ungrouped
  gather_facts: False
  roles:
    - common

- hosts: desktop
  gather_facts: False
  roles:
    - desktop
