---
- block:
  - name: Configure portage
    template: src=make.conf.j2 dest=/etc/portage/make.conf

  - name: Create repos.conf
    file:
      path: /etc/portage/repos.conf
      state: directory

  - name: Add gentoo repository
    copy:
      src: /usr/share/portage/config/repos.conf
      dest: /etc/portage/repos.conf/gentoo.conf

  - name: Add qgp repository
    copy:
      src: qgp.conf
      dest: /etc/portage/repos.conf/qgp.conf
    notify: "sync portage"

  - name: Initialize portage
    tags: test
    shell:
      emerge-webrsync
      creates=/usr/portage
    notify: "sync portage"

  - name: Install gentoolkit
    shell:
      emerge -n gentoolkit
      creates=/usr/bin/equery

  - name: Install git
    portage: package=dev-vcs/git state=latest

  - name: Select profile
    shell:
      eselect profile set qgp:default/systemd

  always:
   - meta: flush_handlers

- name: Update @world
  shell:
    emerge -DuN @world

- name: Install kernel sources & GRUB
  portage:
    state=latest
    package=sys-kernel/gentoo-sources
    package=grub

#- name: Build kernel
#  shell: "cd /usr/src/linux && make defconfig && scripts/config -d CONFIG_BLK_DEV_INITRD && make -j 8 && make install && make modules_install"

- name: Install packages
  portage:
    state: latest
    package:
      - netifrc
      - syslog-ng
      - fcron
      - openssh
      - dhcpcd
