---
- block:
  - name: test
    debug:
      msg: "msg: {{ ar[0], ar[2] }}"

  - name: Configure portage
    template:
      src: make.conf.j2
      dest: /etc//portage/make.conf

  - name: Create repos.conf
    file:
      path: /etc/portage/repos.conf
      state: directory

  - name: Add gentoo repository
    copy:
      src: gentoo.conf
      dest: /etc/portage/repos.conf/gentoo.conf

  - name: Add qgp repository
    copy:
      src: qgp.conf
      dest: /etc/portage/repos.conf/qgp.conf
    notify: "sync portage"

  - name: Initialize portage
    tags: test
    shell: emerge-webrsync
    args:
      creates: /usr/portage
    notify: "sync portage"

  - name: Install gentoolkit
    shell: emerge -n gentoolkit
    args:
      creates: /usr/bin/equery

  - name: Install git
    portage: package=dev-vcs/git state=present

  - name: Select profile
    shell:
      eselect profile set qgp:default/systemd

  - name: Create directory for use flags
    file:
      path: /etc/portage/package.use
      state: directory

  - name: Set use flags
    copy:
      src: 10_ansible
      dest: /etc/portage/package.use/10_ansible

  always:
   - meta: flush_handlers

- name: Update @world
  portage:
    package: '@world'
    update: yes
    deep: yes

- name: Install packages
  portage:
    state: latest
    package:
      - sys-kernel/gentoo-sources
      - grub
      - netifrc
      - syslog-ng
      - fcron
      - openssh
      - dhcpcd

#- name: Build kernel
#  shell: "cd /usr/src/linux && make defconfig && scripts/config -d CONFIG_BLK_DEV_INITRD && make -j 8 && make install && make modules_install"
