---
- name: Configure portage
  template: src=make.conf.j2 dest=/etc/portage/make.conf

- name: Configure gentoo repo
  template: src=gentoo.conf.j2 dest=/etc/portage/repos.conf/gentoo.conf

- name: Configure qgp repo
  template: src=qgp.conf.j2 dest=/etc/portage/repos.conf/qgp.conf

- name: Update qgp repository
  tags: [ 'never', 'debug' ]
  action: shell emaint sync -r qgp

- name: Install @powerweek
  portage: package=@powerweek state=latest usepkgonly=yes

- name: Configure LDAP authentication
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'ldap/nsswitch.conf', dest: '/etc/' }
    - { src: 'ldap/system-auth', dest: '/etc/pam.d/' }
    - { src: 'ldap/system-login', dest: '/etc/pam.d/' }
    - { src: 'ldap/ldap.conf', dest: '/etc/' }
    - { src: 'ldap/openldap/ldap.conf', dest: '/etc/openldap/' }

- name: Configure ssh
  copy: src=sshd_config dest=/etc/ssh/

- name: Fix Qt
  copy: src=90_xkb.sh dest=/etc/profile.d/
